name: Publish release summary to discord

on:
  release:
    types: [published]

jobs:
  publish-release-summary-to-discord:
    runs-on: ubuntu-latest
    name: Github Releases To Discord
    steps:
      - name: Sending message
        uses: nhevia/discord-styled-releases@main
        with:
          webhook_id: "1121127603496034415"
          webhook_token: "f-C87wJCJRtMFaxYrUKdh_06-mQXRkcInCgLL1ztVZsKjzNWyfenFkUWjVefXB82I6wA"

